name: test compilation
on:
  push:
    branches:
      - main
    tags:
      - v1     
jobs:
  job_1:
    name: Compilation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: compilation
      run: |
        make
